---
abstract: 'update file access and modification times, optionally creating files if needed'
author:
  - 'Nigel Wetters Gourlay <nwetters@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Touch
requires:
  Carp: '0'
  Exporter: '0'
  Fcntl: '0'
  File::stat: '0'
  IO::File: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/File-Touch
  repository: https://github.com/neilbowers/File-Touch.git
version: '0.09'
